routes/web.php
<?php

use App\Http\Controllers\ProductsController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route( 'products.index' );
})->name('home.index');

Route::resource( 'products', ProductsController::class );

Auth::routes();

Route::get('/home', [ProductsController::class, 'index'])->name('home');

app/Models/ProductAttributes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductAttributes extends Model
{
    use HasFactory, SoftDeletes;

    public function products()
    {
        return $this->belongsTo('App\Models\Products' );
    }
}

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Products extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
    ];

    public function productAttributes()
    {
        return $this->hasMany('App\Models\ProductAttributes' );
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Products;
use Illuminate\Http\Request;

class ApiController extends Controller
{

    public function getProduct( $id )
    {
        $product = Products::findOrFail( $id );

        return response()
            ->json( [ 'product' => $product->toArray(), 'attributes' => $product->productAttributes->toArray() ] )
            ->header( 'Content-Type', 'application/json' );
    }

    public function getProducts()
    {
        return response()->json( [ 'products' => Products::all()->toArray() ] );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProducts;
use App\Models\Products;

class ProductsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view( 'products.index', [ 'products' => Products::all() ] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'products.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreProducts $request
     * @return \Illuminate\Http\Response
     */
    public function store( StoreProducts $request )
    {
        $validated                  = $request->validated();
        $product                    = new Products();

        $product->fill( $validated );
        $product->save();

        session()->flash( 'status', 'New Product created!' );
        return redirect()->route( 'products.show', [ 'product' =>$product->id ] );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( $id )
    {
        return view( 'products.show', [ 'product' => Products::findOrFail( $id ) ] );

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $id )
    {
        return view( 'products.edit', [ 'product' => Products::findOrFail( $id ) ] );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreProducts $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update( StoreProducts $request, $id )
    {
        $validated                  = $request->validated();
        $product                    = Products::findOrFail( $id );

        $product->fill( $validated );
        $product->save();

        session()->flash( 'status', 'Product updated!');
        return redirect()->route( 'products.show', [ 'product' => $product->id ] );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id )
    {
        $product = Products::findOrFail( $id );
        $product->delete();

        session()->flash( 'status', 'Product deleted!');
        return redirect()->route( 'products.index' );
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }} - @yield( 'title' )</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                <img src="{{ asset( 'logo.png' ) }}" width="50px" height="50px" alt="">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="nAavbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('title', 'Create Product')

@section('content')
    <div class="container">
        <div class="list-group list-group-horizontal-md mb-sm-2 mb-md-3 mb-lg-4">
            <a class="list-group-item list-group-item-action list-group-item-primary text-center col-sm-12 col-md-2 col-lg-1" href="{{ route( 'products.index' ) }}">Back</a>
        </div>
        <div>
            <form action="{{ route( 'products.store' ) }}" method="POST">
                @csrf
                @include( 'products.partials.form' )
                <div class="list-group">
                    <button class="list-group-item list-group-item-action list-group-item-success text-center col-sm-12 col-md-3 col-lg-2" type="submit">Create</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends( 'layouts.app' )

@section( 'title', 'Edit Product' )

@section( 'content' )
    <div class="container">
        <div class="list-group list-group-horizontal-md mb-sm-2 mb-md-3 mb-lg-4">
            <a class="list-group-item list-group-item-action list-group-item-primary text-center col-sm-12 col-md-3 col-lg-1" href="{{ route( 'products.show', [ 'product' => $product->id] ) }}">Back</a>
        </div>
        <div>
            <form action="{{ route( 'products.update', [ 'product' => $product->id ] ) }}" method="POST">
                @csrf
                @method('PUT')
                @include( 'products.partials.form' )
                <div class="list-group">
                    <button class="list-group-item list-group-item-action list-group-item-success text-center col-sm-12 col-md-3 col-lg-2" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends( 'layouts.app' )

@section( 'title', 'Products List' )

@section( 'content' )
    <div class="container">
        <div class="list-group list-group-horizontal-md mb-sm-2 mb-md-3 mb-lg-4">
            <a class="list-group-item list-group-item-action list-group-item-primary text-center col-sm-12 col-md-4 col-lg-3" href="{{ route( 'products.create') }}">Add New Product</a>
        </div>
        <div class="cl-sm-12 cl-md-12 cl-lg-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Created</th>
                        <th scope="col">Updated</th>
                        <th scope="col">Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $products as $product )
                        <tr>
                            <th scope="row">{{ $product->id }}</th>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->description }}</td>
                            <td>{{ $product->created_at }}</td>
                            <td>{{ $product->updated_at }}</td>
                            <td><a href="{{ route('products.show', [ 'product' => $product->id ]) }}">Details</a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/products/partials/form.blade.php
<div class="form-row">
    <div class="col-md-4 mb-4">
        <label for="product_name">Product Name</label>
        <input class="form-control @error('name') is-invalid @enderror" id="product_name" type="text" name="name" value="{{ old( 'name', optional( $product ?? null )->name ) }}">
        @error('name')
        <div class="invalid-feedback">
            <span>{{ $message }}</span>
        </div>
        @enderror
    </div>
</div>
<div class="form-row">
    <div class="col-md-4 mb-4">
        <label for="product_description">Product Description</label>
        <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="product_description" >{{ old( 'description', optional( $product ?? null )->description ) }}</textarea>
        @error('description')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
        @enderror
    </div>
</div>

resources/views/products/show.blade.php
@extends( 'layouts.app' )

@section( 'title', 'Product' )

@section( 'content' )
    <div class="container">
        <div class="list-group list-group-horizontal-md mb-sm-2 mb-md-3 mb-lg-4">
            <div class="list-group list-group-horizontal-md col-md-3 col-lg-2">
                <a class="list-group-item list-group-item-action list-group-item-primary text-center col-md-5" href="{{ route( 'products.index' ) }}">Back</a>
                <a class="list-group-item list-group-item-action list-group-item-warning text-center col-md-7" href="{{ route( 'products.edit', [ 'product' => $product->id ] ) }}">Edit</a>
            </div>
            <div class="list-group list-group-horizontal-md col-md-3">
                <form class="" method="POST" action="{{ route( 'products.destroy', [ 'product' => $product->id ]) }}">
                    @csrf
                    @method('DELETE')
                    <div>
                        <button class="list-group-item list-group-item-action list-group-item-danger text-center rounded-sm" type="submit">Delete</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="card bg-light mb-3 col-12 col-sm-12 col-md-6 col-lg-4">
                <div class="card-header bg-transparent">Product #{{ $product->id }}</div>
                <div class="card-body">
                    <h5 class="card-title">Product Name</h5>
                    <p class="card-text">{{ $product->name }}</p>
                    <h5 class="card-title">Product Description</h5>
                    <p class="card-text">{{ $product->description }}</p>
                </div>
                <div class="card-footer bg-transparent">
                    <span>Created: {{ $product->created_at }}</span>
                    <br>
                    <span>Updated: {{ $product->updated_at }}</span>
                </div>
            </div>


            @if( $product->productAttributes->count() > 0 )
                @foreach( $product->productAttributes as $attribute )
                    <div class="card mb-3 col-12 col-sm-12 col-md-6 col-lg-4">
                        <div class="card-header bg-transparent">Product Attribute #{{ $attribute->id }}</div>
                        <div class="card-body">
                            <h5 class="card-title">{{ $attribute->key }}</h5>
                            <p class="card-text">{{ $attribute->value }}</p>
                        </div>
                        <div class="card-footer bg-transparent">
                            <span>Created: {{ $attribute->created_at }}</span>
                            <br>
                            <span>Updated: {{ $attribute->updated_at }}</span>
                        </div>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
@endsection